import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';
import{fromModel,ocrLinesOf,pageDocument,normalize}from'./core.mjs';import{measureDocumentPage}from'./document-page.mjs';import{sourceChoices,sourceTintedTableFrame,sourceTableFrame,sourceColumnRule,sourcePhotoBox,translatedSourceBlock,splitSourceWords}from'./ocr-structure.mjs';import{localizeLayout,validatePage}from'./page-contract.mjs';
const fixtures=JSON.parse(readFileSync(new URL('../../conversion-fixtures/hsk5-source-pages-021-022.json',import.meta.url)));
test('native writing, retelling, vocabulary and source question routing survive the shared renderer',()=>{for(const f of fixtures){let l=fromModel(f.source,f.ocr.width,f.ocr.height);l.theme={};measureDocumentPage(l,{W:100,H:150,at:()=>[255,255,255]},ocrLinesOf(f.ocr));l=localizeLayout(l);assert.deepEqual(validatePage(l,{requireKz:true}).errors,[]);assert.ok(l.blocks.every(b=>!b.unresolvedStructure));const html=pageDocument(l);assert.match(html,/data-en=/);assert.match(html,/data-kz=/);if(f.bookId==='9b495a8351c6'&&f.sourcePage===21){assert.equal((html.match(/hsk-source-retelling/g)||[]).length,3);assert.equal((html.match(/data-insertion-question=/g)||[]).length,4);assert.match(html,/data-hsk-speak="离婚"/);assert.equal(l.blocks.filter(b=>b.documentText?.badge).length,14);}if(f.bookId==='9b495a8351c6'&&f.sourcePage===22){for(const w of['脑袋','脖子','肩膀','胸','腰','后背','手指','眉毛','嗓子','牙齿'])assert.ok(html.includes('data-hsk-speak="'+w+'"'));assert.equal(l.blocks.filter(b=>b.type==='image'&&!b.documentGraphic).length,1);}if(f.bookId==='1a3750a2f488'&&f.sourcePage===21){const choices=sourceChoices(f.ocr.lines);assert.equal(choices.length,12);for(const q of[26,27,28])assert.deepEqual(choices.filter(c=>c.question===q).map(c=>c.letter),['A','B','C','D']);assert.doesNotMatch(html,/data-correct=/);}if(f.bookId==='1a3750a2f488'&&f.sourcePage===22){assert.match(html,/data-hsk-speak="打工"/);assert.match(html,/data-hsk-speak="亮"/);}}});
test('pale cells yield their actual white row and column separators rather than ink fragments',()=>{const g={W:300,H:300,at:(x,y)=>{if(x<50||x>250||y<60||y>170||[90,91,130,131].includes(y)||[149,150,151].includes(x))return[255,255,255];return x<150?[220,245,205]:[240,210,250];}},f=sourceTintedTableFrame(g,[{box:{x:.23,y:.23,w:.50,h:.30}}]);assert.equal(f.rowEdges.length,4);assert.ok(Math.abs(sourceColumnRule(g,f,.49)-.5)<.01);assert.ok(f.whiteRules);});
test('multiple short printed blanks retain separate pixel-based answer slots',()=>{const lines=[{text:'请',box:{x:.2,y:.2,w:.08,h:.03}},{text:'不要',box:{x:.39,y:.2,w:.08,h:.03}},{text:'他',box:{x:.58,y:.2,w:.04,h:.03}}],source={blocks:[translatedSourceBlock(lines,{en:'Please ___; do not ___ him.',ru:'Пожалуйста, ___; не ___ его.'},{options:{gapAnswers:true}})]},l=fromModel(source,1000,1400);l.theme={};measureDocumentPage(l,{W:1000,H:1400,at:(x,y)=>y===319&&((x>=285&&x<=385)||(x>=475&&x<=575))?[160,160,160]:[255,255,255]},lines);assert.equal(l.blocks.filter(b=>b.answerField).length,2);assert.equal(l.blocks[0].documentText.gapAnswers.length,2);assert.match(pageDocument(l),/data-gap-answers=/);});
test('a photograph is cropped from free column pixels without swallowing neighbouring text',()=>{const g={W:200,H:200,at:(x,y)=>x>=140&&x<180&&y>=80&&y<130?[170,80,60]:[255,255,255]},q=sourcePhotoBox(g,{x:.65,y:.35,w:.3,h:.35});assert.ok(Math.abs(q.x-.7)<.01);assert.ok(Math.abs(q.h-.25)<.01);});
test('source pages with many independent interactive tokens are not truncated at sixty blocks',()=>{const source=Array.from({length:73},(_,i)=>({type:'text',box:{x:.1,y:.1+i*.005,w:.2,h:.003},cn:String(i)}));assert.equal(normalize(source).length,73);});

test('a dark header ribbon excludes a separate side heading from the table frame',()=>{const g={W:400,H:400,at:(x,y)=>{if(x>=100&&x<=360&&y>=60&&y<=85)return[75,60,140];if(x>=65&&x<=80&&y>=65&&y<=77)return[75,60,140];if(x>=100&&x<=360&&y===140)return[100,100,100];return[255,255,255];}},f=sourceTableFrame(g,[{box:{x:.27,y:.17,w:.5,h:.16}}]);assert.ok(Math.abs(f.box.x-.25)<.01);assert.equal(f.rowEdges.length,3);});
test('real whitespace splits a merged word-bank line at source ink rather than distributing its width',()=>{const g={W:400,H:400,at:(x,y)=>y>=80&&y<=90&&((x>=81&&x<=91)||(x>=131&&x<=141))?[40,40,40]:[255,255,255]},parts=splitSourceWords(g,{box:{x:.2,y:.2,w:.16,h:.03}},['是','的']);assert.ok(Math.abs(parts[0].box.x-.2025)<.005);assert.ok(parts[0].box.w<.04);assert.ok(Math.abs(parts[1].box.x-.3275)<.005);});
