// Reusable translations for recognised picture labels, independent of pages.
export const wordLabels = {
  '衣服':{en:'clothes',kk:'киім'},'漂亮':{en:'beautiful',kk:'әдемі'},'早上':{en:'morning',kk:'таңертең'},
  '妈妈':{en:'mother',kk:'ана'},'爸爸':{en:'father',kk:'әке'},'水果':{en:'fruit',kk:'жемістер'},'哪里':{en:'where',kk:'қайда'},'小语':{en:'Xiaoyu',kk:'Сяоюй'},'饺子':{en:'dumpling',kk:'тұшпара'},
  '人':{en:'person',kk:'адам'},'坐':{en:'to sit',kk:'отыру'},'菜':{en:'vegetables',kk:'көкөністер'},'书':{en:'book',kk:'кітап'},
  '手机':{en:'mobile phone',kk:'ұялы телефон'},'医生':{en:'doctor',kk:'дәрігер'},'桌子':{en:'table',kk:'үстел'},'出租车':{en:'taxi',kk:'такси'},
  '春':{en:'spring',kk:'көктем'},'村':{en:'village',kk:'ауыл'},'睡':{en:'to sleep',kk:'ұйықтау'},'嘴':{en:'mouth',kk:'ауыз'},
  '鸡':{en:'chicken',kk:'тауық'},'七':{en:'seven',kk:'жеті'},'写':{en:'to write',kk:'жазу'},'请':{en:'please; to invite',kk:'өтінемін; шақыру'},
  '再见':{en:'goodbye',kk:'сау бол'},'谢谢':{en:'thank you',kk:'рақмет'},'星期':{en:'week',kk:'апта'},'高兴':{en:'happy',kk:'қуанышты'},
  '雨':{en:'rain',kk:'жаңбыр'},'五':{en:'five',kk:'бес'},'一':{en:'one',kk:'бір'},'椅子':{en:'chair',kk:'орындық'},
  '九':{en:'nine',kk:'тоғыз'},'牛奶':{en:'milk',kk:'сүт'},'休息':{en:'to rest',kk:'демалу'},
  '口':{en:'mouth',kk:'ауыз'},'饭':{en:'cooked rice',kk:'күріш'},'喝':{en:'to drink',kk:'ішу'},'二':{en:'two',kk:'екі'},
  '你好':{en:'hello',kk:'сәлем'},'朋友':{en:'friend',kk:'дос'},'面包':{en:'bread',kk:'нан'},'妹妹':{en:'younger sister',kk:'сіңлі / қарындас'},
  '房间':{en:'room',kk:'бөлме'},'白天':{en:'daytime',kk:'күндіз'},'饭店':{en:'restaurant',kk:'мейрамхана'},'电脑':{en:'computer',kk:'компьютер'}
};
export const phoneticPhraseLabels={
 'pěngchǎng':{hz:'捧场',ru:'поддержать выступление',en:'support a performance',kk:'өнер көрсетушіні қолдау'},
 'hǎojiǔ':{hz:'好久',ru:'давно; долго',en:'a long time',kk:'ұзақ уақыт'},
 'wǎndiǎn':{hz:'晚点',ru:'опаздывать',en:'be late',kk:'кешігу'},
 'liǎojiě':{hz:'了解',ru:'понимать; знать',en:'understand',kk:'түсіну'},
 'xǐzǎo':{hz:'洗澡',ru:'принимать душ',en:'take a shower',kk:'душ қабылдау'},
 'zhǐyǒu':{hz:'只有',ru:'только',en:'only',kk:'тек'},
 'bāozi':{hz:'包子',ru:'паровая булочка',en:'steamed bun',kk:'буға пісірілген тоқаш'},
 'xièxie':{hz:'谢谢',ru:'спасибо',en:'thank you',kk:'рақмет'},
 'piányi':{hz:'便宜',ru:'дешёвый',en:'inexpensive',kk:'арзан'},
 'dìdi':{hz:'弟弟',ru:'младший брат',en:'younger brother',kk:'іні'},
 'piàoliang':{hz:'漂亮',ru:'красивый',en:'beautiful',kk:'әдемі'},
 'méiguānxi':{hz:'没关系',ru:'ничего страшного',en:'that is OK',kk:'оқасы жоқ'},
 'duìbuqǐ':{hz:'对不起',ru:'извините',en:'sorry',kk:'кешіріңіз'},
 'duibuqǐ':{hz:'对不起',ru:'извините',en:'sorry',kk:'кешіріңіз',printedPy:'duìbuqǐ'},
 'rènshi':{hz:'认识',ru:'знать; быть знакомым',en:'know; be acquainted',kk:'тану; таныс болу'},
 'sūnzǐ':{hz:'孙子',ru:'Сунь-цзы, военный стратег',en:'Sun Tzu, military strategist',kk:'Сунь-цзы, әскери стратег'},
 'sūnzi':{hz:'孙子',ru:'внук',en:'grandson',kk:'немере'},
 'dōngxī':{hz:'东西',ru:'восток и запад',en:'east and west',kk:'шығыс пен батыс'},
 'dōngxi':{hz:'东西',ru:'вещи',en:'things',kk:'заттар'},
 'yùnqì':{hz:'运气',ru:'регулировать дыхание',en:'control breathing',kk:'тынысты реттеу'},
 'yùnqi':{hz:'运气',ru:'удача',en:'luck',kk:'сәттілік'},
 'lǎozǐ':{hz:'老子',ru:'Лао-цзы, философ',en:'Lao Tzu, philosopher',kk:'Лао-цзы, философ'},
 'lǎozi':{hz:'老子',ru:'отец; я (грубое выражение)',en:'father; I (coarse expression)',kk:'әке; мен (дөрекі сөз)'},
 'dìfāng':{hz:'地方',ru:'местность; регион',en:'region; locality',kk:'аймақ; өңір'},
 'difāng':{hz:'地方',ru:'местность; регион',en:'region; locality',kk:'аймақ; өңір',printedPy:'dìfāng'},
 'dìfang':{hz:'地方',ru:'место',en:'place',kk:'орын'},
 'mǎmǎhūhū':{hz:'马马虎虎',ru:'так себе; небрежно',en:'so-so; careless',kk:'орташа; ұқыпсыз'},
 'mǎhu':{hz:'马虎',ru:'небрежный',en:'careless',kk:'ұқыпсыз'},
 'shuǐguǒ':{hz:'水果',ru:'фрукты',en:'fruit',kk:'жемістер'},'nǐhǎo':{hz:'你好',ru:'здравствуйте',en:'hello',kk:'сәлем'},
 'kěyǐ':{hz:'可以',ru:'можно',en:'can; may',kk:'болады'},'nǎlǐ':{hz:'哪里',ru:'где',en:'where',kk:'қайда'},
 'hěnhǎo':{hz:'很好',ru:'очень хорошо',en:'very good',kk:'өте жақсы'},'suǒyǐ':{hz:'所以',ru:'поэтому',en:'therefore',kk:'сондықтан'},
 'qǐngnǐ':{hz:'请你',ru:'прошу вас',en:'please',kk:'сізден өтінемін'},'shǒubiǎo':{hz:'手表',ru:'наручные часы',en:'wristwatch',kk:'қол сағаты'}
};
